### ISSUE TITLE
Improve performance and error handling

### ISSUE THREAD

**Issue by itsnikhil** [SergioMorchon/fitbit-views#5]
I refactored my app code to use Multi View SDK but the performance is just not good. I wasn't able to identify errors properly as they all pointed to views.js try catch. Now I have to scrap all the work put into the update (´;︵;`)

I wanted to divide my views as index.js and index.gui because they were getting large and hard to manage. But at least the performance was way better. I even faced memory errors while swapping of views and fitbit simulator randomly sometimes randomly crash upon me throwing Internal Error.

Is they any way to make swapping of views asynchronous or anything that improves the performance. Please update it!

**Comment by SergioMorchon** [comment]
Hi @itsnikhil!
First of all, I have a few questions:
- What is the "Multi View SDK"?
- Can you post the errors or some code around them?

And finally:
- how would you improve the _performance_?

This small library makes easier to load different GUI files while creating & disposing each view resources.
Nothing less, and nothing more.
That won't avoid you the requirement of pargins & loading all your code.
If you have a lot of functions / objects etc., this won't make a difference: it's just a map that call your functions.

If you really need to split your views, then you'll need to use async imports (`import('./view-1.js` for example) but also handle it maually.

Just in case, I have both working examples:
- With this project: https://github.com/SergioMorchon/fitbit-geolocator/tree/master/app/components
- With async `import()`: https://github.com/SergioMorchon/fitbit-pokelab-swsh/tree/master/app/views

**Comment by itsnikhil** [comment]
Oops I am extremely sorry I created the issue on different Repo

This is MultiView for fitbit- https://github.com/Fitbit/sdk-multi-view

Hey, yours does the same task and I will give it a shot if the performance is fine or not

Thanks for the quick reply and again I am really really really sorry for opening an issue at wrong place. Do you know how can I delete it?

**Comment by SergioMorchon** [comment]
Oh, don't worry
I think that one is an example to demonstrate the new capabilities introduced in previous versions of Fitbit SDK (and some of them are used here too).
I think you can give this a try if you think it may help, of course

**Comment by itsnikhil** [comment]
Hi there, I have switched to your multi view implementation yesterday and it seems to work better but still there is a bit of a delay in loading one of my view (it is a bit heavy)

I wanted you to answer some of questions below

- I was not able to understand async import you were talking about. Currently there is a delay of ~1&nbsp;sec to load next view. With async loading I can play a loading animation while next view loads asynchronously in background.
- How to know which view is currently opened (something like getCurrentViewByName). I want to reload of the same view
- I was testing my app with your memory debug script, I was getting numbers around `Memory: 0.68 (2520B), peak 0.68, pressure normal`. Is it good or bad?

Hope my questions makes sense. I would be waiting for your response
