### ISSUE TITLE
Unable to determine last page easily

### ISSUE THREAD

**Issue by mikebowyer** [SergioMorchon/fitbit-views#7]
Hi @SergioMorchon,

First of all, thank you for implementing fitbit-views. It's makes transitions between different screens in an app very easy!

I am having trouble achieving the functionality in my app that I want due to the current current API implementation. My problem is that I am unable to determine which view brought me to the current view, and I am unable to know exactly what view _back()_ will return me too (if at all!).

For example, if I have 3 views (A, B and C) and both views A&B have ability to call _next('C')_, I would like understand which view (A or B) caused me to enter view C. This would enable different functionality in view C depending on what the previous view was.  But currently, this seems impossible because the the stack is not exported, and there is no way to know what view the _back()_ would take me to. 

Could you somehow expose the stack and make a getter function for it that allows people to see the sequence of views which caused the app to arrive at the current view? 

Thanks for your help, let me know if I can aid in anyway!

**Comment by SergioMorchon** [comment]
Hi!
Thanks for writing.
I though about exposing the stack or not, and finally decided to not doing it:
* Web standards, that Fitbit SDK aims to be inspired on it, doesn0t allow to query the history URLs.
* Instead, for this particular use case, you can pass a parameter when calling next & back:
** [`next(viewId, params)`](https://github.com/SergioMorchon/fitbit-views/blob/v1.0.3/__tests__/index-test.js#L67).
** [`back(params)`](https://github.com/SergioMorchon/fitbit-views/blob/v1.0.3/__tests__/index-test.js#L105).

That way you could do
*a.js*
```typescript
export default ({from}) => {
  console.log(from);// undefined the first time, and 'b' when coming back from b.js view
  next('b', {from: 'a'});
}
```
*b.js*
```typescript
export default ({from}) => {
  console.log(from);// 'a'
  back({from: 'b'});
});
```

**Comment by mikebowyer** [comment]
Thanks Sergio, that is very helpful and exactly what I needed. I agree your decision and implementation is a better one. 

May i suggest you add the example you have shown in this thread into the README.md? I read it and it was not clear to me exactly how to use it. 

Thanks again!

**Comment by SergioMorchon** [comment]
Sure, I'll do.
Thank you for your feedback!
