### ISSUE TITLE
How to disable Phsyical button back(), or pass paremeter with back button press?

### ISSUE THREAD

**Issue by mikebowyer** [SergioMorchon/fitbit-views#9]
Hi again,

I am having some trouble with parameter passing using the physical back button. I will first explain the situation: 

I have a view B, which I entered using `next('views/B', {from: 'A');` from view A. This now means that view B expects the parameter "from" whenever entering that view. 

The problem arises when I leave view B for view C, and when in view C the physical back button is pressed. This causes the regular back(), function to be called which means no parameter is passed back to view B, causing view B to produce the error: 
   App: Unhandled exception: TypeError: wrong type of argument                        ((null):1,1)
   App: Unhandled exception: TypeError: Cannot read property 'from' of undefined
  ? at app/views/B.js

Is there someway to do either of the following?
   1) Disable the physical back button on some views?
   2) Pass parameters in the back() function when the physical back button is pressed? 

Thanks again for your help!

**Comment by SergioMorchon** [comment]
Yes, you can definitely do that with `buttons.back` callback, and the `back` function.
Indeed I've detected I had it bad documented, and fixed [here](https://github.com/SergioMorchon/fitbit-views/commit/5a814b249665a05a7808d58129e2fdd45f7d5d82) .

Just follow [this instructions](https://github.com/SergioMorchon/fitbit-views#whats-in-the-box), under the `buttons` section:
```javascript
import { buttons, back } from 'fitbit-views';

export default () => {
	buttons.back = () => {
		if (someCondition) {
			back();
		}

		// else, nothing happens: no navigation
	};
};
```

And a working real example: https://github.com/SergioMorchon/fitbit-geolocator/blob/v1.3.0/app/components/details.ts#L57-L63

**Comment by mikebowyer** [comment]
This is exactly what I was looking for. Thanks a lot!
